variables:
  NODE_IMAGE: node:latest
  GO_IMAGE: golang:latest
  HUGO_VERSION: 0.71.0

stages:
  - build
  - deploy

build:
  stage: build
  image: $GO_IMAGE
  only:
    - master
  script:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - make build
    - make gzip
  artifacts:
    paths:
    - public

deploy:
  image: $NODE_IMAGE
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify --telemetry-disable
    - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_AUTH_TOKEN} --prod
  only:
    - master


# pages:
#   image: $GO_IMAGE
#   only:
#     - master
#   script:
#     - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
#     - dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
#     - make build
#     - make gzip
#   artifacts:
#     paths:
#     - public
