variables:
  GO_IMAGE: golang:latest
  HUGO_VERSION: 0.62.1

pages:
  image: $GO_IMAGE
  script:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
    - dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
    - make build
    - gzip -k -9 -r -f public
  artifacts:
    paths:
    - public
