baseURL = "https://fatalentropy.com"
languageCode = "en-us"
title = "Fatal Entropy"
disableHugoGeneratorInject = true
enableGitInfo = true

[author]
  name = "Sylvain Kerkour"
  email = "hello@fatalentropy.com"

[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[params]
  description = "Strong opinions and crazy ideas on tech, open source, entrepreneurship and everything in between. By Sylvain Kerkour, creator of Bloom."
  descriptionHtml = """
    Strong opinions and crazy ideas on tech, open source, entrepreneurship and everything in between. By Sylvain Kerkour, creator of
      <a target="_blank" href="https://www.bloom.sh" rel="noopener" style="color: yellow; text-decoration: underline;">Bloom</a>.
    """
  git = "https://gitlab.com/bloom42/blog"
  obfuscatedEmail = '<n uers="znvygb:flyinva@xrexbhe.se">flyinva@xrexbhe.se</n>'
  # uryyb@sngnyragebcl.pbz
  ogimage = "https://fatalentropy.com/imgs/og_image.jpg"


[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "jsonfeed"]
