baseURL = "https://bloom42.gitlab.io/blog"
languageCode = "en-us"
title = "My New Hugo Site"
descriotion = "Strong opinions and crazy ideas on design, tech and humanity. By the creators of Bloom."
# theme = "vienna"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
