baseURL = "https://bloom42.gitlab.io/blog"
languageCode = "en-us"
title = "My New Hugo Site"
descriotion = "My description"
# theme = "vienna"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
