baseURL = "https://fatalentropy.com"
languageCode = "en-us"
title = "Fatal Entropy"
disableHugoGeneratorInject = true


[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[params]
  description = "Strong opinions and crazy ideas on open source tech, entrepreneurship and everything in between. By the creators of Bloom."
  descriptionHtml = """
    Strong opinions and crazy ideas on open source tech, entrepreneurship and everything in between. By the creators of
      <a target="_blank" href="https://www.bloom.sh" rel="noopener" style="color: yellow; text-decoration: underline;">Bloom</a>.
    """
  git = "https://gitlab.com/bloom42/blog"
