[Settings]

[build]
  publish = "public/"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = '''
    public,
    max-age=3600,
    s-maxage=31536000
    '''


####################################################################################################
### www.fatalentropy.com
####################################################################################################

# [[redirects]]
#   from = "https://bloom42-blog.netlify.app/*"
#   to = "https://www.fatalentropy.com/:splat"
#   status = 301
#   force = true


[[redirects]]
  from = "https://fatalentropy.com/*"
  to = "https://www.fatalentropy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/index.xml"
  to = "/feed.xml"
  status = 301
