[Settings]

[build]
  publish = "public/"


####################################################################################################
### fatalentropy.com
####################################################################################################

[[redirects]]
  from = "https://www.fatalentropy.com/*"
  to = "https://fatalentropy.com/:splat"
  status = 301
  force = true
